### ISSUE TITLE
2.0 alpha checklist

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#1395]
Things that absolutely must be done by March 30th, which is when I tag `v2.0a1` on the `main` branch no matter what.  That's because of promises for certain functionality that will be in the paper.

Everything here that's a feature/change is in the context of the new parser combinator code that's being added and not the existing monolithic classes.

- milestone: https://github.com/cclib/cclib/milestone/24
- paper: https://github.com/cclib/cclib/issues/1340
- parser combinators: https://github.com/cclib/cclib/issues/335, https://github.com/cclib/cclib/issues/1124
- parser-in-parser: https://github.com/cclib/cclib/issues/131, https://github.com/cclib/cclib/issues/132, https://github.com/cclib/cclib/issues/657
- attributes as classes: https://github.com/cclib/cclib/issues/99, https://github.com/cclib/cclib/issues/419

Things not promised in the paper but people should be prepared for, or they'll be angry if any of this is a surprise.

- atomic units w/ unit objects: https://github.com/cclib/cclib/issues/89, https://github.com/cclib/cclib/issues/998, https://github.com/cclib/cclib/issues/1264
- testing: https://github.com/cclib/cclib/issues/1394

I think for the output units those changes can go into the existing infrastructure too, but on the `main` branch.  When 2.0 is finally released, which is when all existing functionality is transitioned to the new parser combinators, we will switch the default branch from `master` to `main`.

cc @oliver-s-lee This is the basic roadmap you asked for in https://github.com/cclib/cclib-data/pull/166#issuecomment-1978208687. The full 2.0 IMO is polishing whatever's in the alpha, but we reserve the right to keep adding API-breaking features, and there is no hard deadline for the final 2.0 release.

Please add stuff I am forgetting.

**Comment by berquist** [comment]
cc @langner

**Comment by shivupa** [comment]
Per our discussion today these are the remaining development tasts

- [ ] Testing
- [ ] Merge open PRs
- [ ] Attributes as classes use/extension (@berquist)
- [ ] Port more parsers

**Comment by berquist** [comment]
The release is done at https://github.com/cclib/cclib/releases/tag/v2.0a1.  I don't want to close any of the referenced issues, since they aren't fully done, so I'm repurposing this issue.

**Comment by Andrew-S-Rosen** [comment]
Out of curiosity, what is the status with 2.0?

**Comment by shivupa** [comment]
We are a little behind for the official release of 2.0 although I'm not sure we set an official date. The main blocker is porting old parsers over to version 2. The things in this list (deliverables for the paper) are completed.

**Comment by Andrew-S-Rosen** [comment]
Should we mention the cclib 2.0 paper on the current README in the menatime?

**Comment by amandadumi** [comment]
Good question! Here is a status update.

We have started porting Gaussian, Psi4, Orca, QChem, and NBO. The attributes that have been ported to version 2 are summarized in the table below, roughly adapted from the '[development parsed data](https://cclib.github.io/data_dev.html)' page of the docs:


Legend:
TBP : 'to be ported'. i.e. the ability to parse the attribute  exists in version 1, but has yet to be ported.
the check mark: the attribute has been ported
T/D:  the attribute is possible to parser, but hasn't been started in version 1 or 2
N/A:  not applicable.


| attributes         | **Gaussian** | **NBO** | **ORCA** | **Psi4** | **QChem** |
| ---------------- | ------------ | ------- | -------- | -------- | --------- |
| aonames            | T/D          | T/D     | TBP      | T/D      | TBP       |
| aooverlaps         | √            | T/D     | TBP      | N/P      | N/P       |
| atombasis          | √            | T/D     | TBP      | √        | √         |
| aaatomcharges      | T/D          | √       | √        | √        | √         |
| atomcoords         | √            | T/D     | TBP      | √        | √         |
| atommasses         | √            | T/D     | TBP      | √        | √         |
| atomnos            | √            | T/D     | TBP      | √        | √         |
| atomspins          | T/D          | T/D     | TBP      | T/D      | TBP       |
| ccenergies         | T/D          | T/D     | TBP      | √        | TBP       |
| charge             | √            | T/D     | TBP      | √        | √         |
| coreelectrons      | √            | T/D     | TBP      | TBP      | TBP       |
| dispersionenergies | T/D          | T/D     | TBP      | √        | TBP       |
| enthalpy           | T/D          | T/D     | TBP      | TBP      | TBP       |
| entropy            | T/D          | T/D     | TBP      | TBP      | TBP       |
| etdips             | T/D          | T/D     | T/D      | T/D      | T/D       |
| etenergies         | T/D          | T/D     | TBP      | T/D      | TBP       |
| etmagdips          | T/D          | T/D     | T/D      | T/D      | T/D       |
| etoscs             | T/D          | T/D     | TBP      | T/D      | TBP       |
| etrotats           | T/D          | T/D     | TBP      | T/D      | N/P       |
| etsecs             | T/D          | T/D     | TBP      | T/D      | TBP       |
| etsyms             | T/D          | T/D     | TBP      | T/D      | TBP       |
| etveldips          | T/D          | T/D     | T/D      | T/D      | T/D       |
| fonames            | N/A          | T/D     | N/A      | N/A      | N/A       |
| fooverlaps         | N/A          | T/D     | N/A      | N/A      | N/A       |
| fragnames          | N/A          | T/D     | N/A      | N/A      | N/A       |
| frags              | N/A          | T/D     | N/A      | N/A      | N/A       |
| freeenergy         | T/D          | T/D     | TBP      | TBP      | TBP       |
| gbasis             | √            | T/D     | TBP      | √        | √         |
| geotargets         | T/D          | T/D     | TBP      | √        | TBP       |
| geovalues          | T/D          | T/D     | TBP      | TBP      | TBP       |
| grads              | T/D          | T/D     | TBP      | TBP      | TBP       |
| hessian            | T/D          | T/D     | T/D      | T/D      | TBP       |
| homos              | T/D          | T/D     | TBP      | TBP      | TBP       |
| metadata           | T/D          | T/D     | TBP      | TBP      | TBP       |
| mocoeffs           | T/D          | T/D     | TBP      | √        | TBP       |
| moenergies         | √            | T/D     | TBP      | TBP      | TBP       |
| moments            | T/D          | T/D     | TBP      | TBP      | TBP       |
| mosyms             | √            | T/D     | TBP      | TBP      | √         |
| mpenergies         | T/D          | T/D     | TBP      | √        | TBP       |
| mult               | √            | T/D     | TBP      | √        | √         |
| natom              | √            | T/D     | TBP      | √        | √         |
| nbasis             | √            | T/D     | TBP      | √        | √         |
| nmo                | √            | T/D     | TBP      | √        | √         |
| nmrcouplingtensors | T/D          | T/D     | TBP      | T/D      | T/D       |
| nmrtensors         | T/D          | T/D     | TBP      | T/D      | T/D       |
| nocoeffs           | T/D          | T/D     | T/D      | T/D      | T/D       |
| nooccnos           | T/D          | T/D     | T/D      | T/D      | T/D       |
| nsocoeffs          | T/D          | T/D     | T/D      | T/D      | T/D       |
| nsooccnos          | T/D          | T/D     | T/D      | T/D      | T/D       |
| optdone            | T/D          | T/D     | TBP      | TBP      | TBP       |
| optstatus          | T/D          | T/D     | T/D      | TBP      | T/D       |
| polarizabilities   | T/D          | T/D     | TBP      | T/D      | TBP       |
| pressure           | T/D          | T/D     | TBP      | T/D      | TBP       |
| rotconsts          | T/D          | T/D     | T/D      | T/D      | T/D       |
| scancoords         | T/D          | T/D     | T/D      | T/D      | T/D       |
| scanenergies       | T/D          | T/D     | T/D      | T/D      | T/D       |
| scannames          | T/D          | T/D     | TBP      | T/D      | T/D       |
| scanparm           | T/D          | T/D     | TBP      | T/D      | T/D       |
| scfenergies        | √            | T/D     | TBP      | √        | √         |
| scftargets         | √            | T/D     | TBP      | √        | TBP       |
| scfvalues          | √            | T/D     | TBP      | TBP      | TBP       |
| temperature        | T/D          | T/D     | TBP      | TBP      | TBP       |
| time               | T/D          | T/D     | T/D      | T/D      | TBP       |
| transprop          | T/D          | T/D     | TBP      | T/D      | T/D       |
| vibanharms         | T/D          | T/D     | T/D      | T/D      | T/D       |
| vibdisps           | T/D          | T/D     | TBP      | TBP      | TBP       |
| vibfconsts         | T/D          | T/D     | T/D      | TBP      | TBP       |
| vibfreqs           | T/D          | T/D     | TBP      | TBP      | TBP       |
| vibirs             | T/D          | T/D     | TBP      | TBP      | TBP       |
| vibramans          | T/D          | T/D     | TBP      | T/D      | TBP       |
| vibrmasses         | T/D          | T/D     | T/D      | TBP      | TBP       |
| vibsyms            | T/D          | T/D     | T/D      | TBP      | T/D       |
| zpve               | T/D          | T/D     | TBP      | TBP      | TBP       |


the porting of the following codes has not been started:  ADF, DALTON, FChk, GAMESS, GAMESSDAT, GAMESSUK, Jaguar, Molpro, Molcas, MOPAC, NWChem, Turbomole, XTB. Incorporating these codes into version 2 will likely be dictated by user interest!

If you'd like more detail on anything specific, let us know!

**Comment by Andrew-S-Rosen** [comment]
I still think we should be linking the new paper on the README otherwise nobody is going to cite it or know it exists. 😉

**Comment by shivupa** [comment]
```
gaussian
--------
atomcharges.py:    known_codes = ["ORCA", "NBO", "psi4", "qchem"]
mocoeffs.py:    known_codes = ["psi4"]

psi4
--------
aooverlaps.py:    known_codes = ["gaussian", "ORCA"]
moenergies.py:    known_codes = ["gaussian", "ORCA"]
nmo.py:    known_codes = ["gaussian", "qchem", "ORCA"]
mosyms.py:    known_codes = ["gaussian", "qchem", "ORCA"]
scfvalues.py:    known_codes = ["gaussian"]
coreelectrons.py:    known_codes = ["gaussian"]
aonames.py:    known_codes = ["gaussian", "ORCA"]

ORCA
--------
moments.py:    known_codes = ["psi4", "gaussian"]
atommasses.py:    known_codes = ["gaussian", "psi4", "qchem"]
dispersionenergies.py:    known_codes = ["psi4", "gaussian"]
scfvalues.py:    known_codes = ["gaussian"]
scftargets.py:    known_codes = ["gaussian", "psi4"]
mpenergies.py:    known_codes = ["psi4", "gaussian"]
geotargets.py:    known_codes = ["psi4", "gaussian"]
coreelectrons.py:    known_codes = ["gaussian"]
scfenergies.py:    known_codes = ["gaussian", "psi4", "qchem"]
ccenergies.py:    known_codes = ["psi4", "gauss

qchem
-----
aooverlaps.py:    known_codes = ["gaussian", "ORCA"]
moments.py:    known_codes = ["psi4", "gaussian"]
moenergies.py:    known_codes = ["gaussian", "ORCA"]
parser_state.py:    known_codes = ["psi4", "ORCA"]
dispersionenergies.py:    known_codes = ["psi4", "gaussian"]
scfvalues.py:    known_codes = ["gaussian"]
scftargets.py:    known_codes = ["gaussian", "psi4"]
mpenergies.py:    known_codes = ["psi4", "gaussian"]
mocoeffs.py:    known_codes = ["ORCA", "psi4"]
geotargets.py:    known_codes = ["psi4", "gaussian"]
coreelectrons.py:    known_codes = ["gaussian"]
ccenergies.py:    known_codes = ["psi4", "gaussian"]
aonames.py:    known_codes = ["gaussian", "ORCA"]

to impl:
-------
        atombasis -- indices of atomic orbitals on each atom (list of lists)
        atomcoords -- atom coordinates (array[3], angstroms)
        atomnos -- atomic numbers (array[1])
        atomspins -- atomic spin densities (dict of arrays[1])
        charge -- net charge of the system (integer)
        enthalpy -- sum of electronic and thermal enthalpies (float, hartree/particle)
        entropy -- entropy (float, hartree/(particle*kelvin))
        etenergies -- energies of electronic transitions (array[1], hartree)
        etoscs -- oscillator strengths of electronic transitions (array[1])
        etdips -- electric transition dipoles of electronic transitions (array[2], ebohr)
        etveldips -- velocity-gauge electric transition dipoles of electronic transitions (array[2], ebohr)
        etmagdips -- magnetic transition dipoles of electronic transitions (array[2], ebohr)
        etrotats -- rotatory strengths of electronic transitions (array[1], ??)
        etsecs -- singly-excited configurations for electronic transitions (list of lists)
        etsyms -- symmetries of electronic transitions (list of string)
        freeenergy -- sum of electronic and thermal free energies (float, hartree/particle)
        fonames -- fragment orbital names (list of strings)
        fooverlaps -- fragment orbital overlap matrix (array[2])
        fragnames -- names of fragments (list of strings)
        frags -- indices of atoms in a fragment (list of lists)
        gbasis -- coefficients and exponents of Gaussian basis functions (PyQuante format)
        geovalues -- current values for convergence of geometry optmization (array[1])
        grads -- current values of forces (gradients) in geometry optimization (array[3])
        hessian -- elements of the force constant matrix (array[1])
        homos -- molecular orbital indices of HOMO(s) (array[1])
        metadata -- various metadata about the package and computation (dict)
        mult -- multiplicity of the system (integer)
        natom -- number of atoms (integer)
        nbasis -- number of basis functions (integer)
        nmrtensors -- Nuclear magnetic resonance chemical shielding tensors (dict of dicts of array[2])
        nmrcouplingtensors -- Nuclear magnetic resonance spin-spin coupling tensors (dict of dicts of array[2])
        nocoeffs -- natural orbital coefficients (array[2])
        nooccnos -- natural orbital occupation numbers (array[1])
        nsocoeffs -- natural spin orbital coefficients (list of array[2])
        nsooccnos -- natural spin orbital occupation numbers (list of array[1])
        optdone -- flags whether an optimization has converged (list of int)
        optstatus -- optimization status for each set of atomic coordinates (array[1])
        polarizabilities -- (dipole) polarizabilities, static or dynamic (list of arrays[2])
        pressure -- pressure used for Thermochemistry (float, atm)
        rotconsts -- rotational constants (array[2], GHz)
        scancoords -- geometries of each scan step (array[3], angstroms)
        scanenergies -- energies of potential energy surface (list)
        scannames -- names of variables scanned (list of strings)
        scanparm -- values of parameters in potential energy surface (list of tuples)
        temperature -- temperature used for Thermochemistry (float, kelvin)
        time -- time in molecular dynamics and other trajectories (array[1], fs)
        transprop -- all absorption and emission spectra (dictionary {name:(etenergies, etoscs)})
        vibanharms -- vibrational anharmonicity constants (array[2], 1/cm)
        vibdisps -- cartesian displacement vectors (array[3], delta angstrom)
        vibfreqs -- vibrational frequencies (array[1], 1/cm)
        vibfconsts -- force constants of vibrations (array[1], mDyne/angstrom)
        vibirs -- IR intensities (array[1], km/mol)
        vibramans -- Raman activities (array[1], A^4/Da)
        vibrmasses -- reduced masses of vibrations (array[1], daltons)
        vibsyms -- symmetries of vibrations (list of strings)
        zpve -- zero-point vibrational energy correction (float, hartree/particle)
```

**Comment by shivupa** [comment]
As we prep release, I want to break how `mocoeffs` are stored. I would also like to add a dimension to `moments` for real time electronic structure calcs

**Comment by berquist** [comment]
> As we prep release, I want to break how `mocoeffs` are stored. I would also like to add a dimension to `moments` for real time electronic structure calcs

`mocoeffs`: $C_{\mu p}$ instead of $C_{p \mu}$

But shouldn't `moments` stay as-is and we go to parsing each frame of MD/RT as individual ccData objects?
