### ISSUE TITLE
Bridge between cclib and horton for Hirshfeld-related charges calculation

### ISSUE THREAD

**Issue by mscho527** [cclib/cclib#880]
_This issue is based on the GSoC proposal._

The aim is to create a bridge between `cclib` and `horton` (both 2 and 3) so that the data parsed with `cclib` can be used to perform Hirshfeld-related population analyses implemented in horton, such as Hirshfeld charges, Iterative Stockholder charges, and Minimal Basis Iterative Stockholder charges.

- [x] #881 Add horton into Travis configuration
- [x] #882 Add stencil code that detects horton version
- [x] #873 Add horton 2 --> cclib bridge, along with tests
- [x] #883 Add cclib --> horton 2 bridge, along with tests
- [x] #884 Add horton 3 --> cclib bridge, along with tests
- [x] #879 Add cclib --> horton 3 bridge, along with tests
- [x] #888 Write documentation for the bridge and how the bridge can be utilized

**Comment by mscho527** [comment]
Closing #892 due to incomplete parsing of .log files in horton 3 at the moment.

**Comment by mscho527** [comment]
Closing issue since each to-do list item has been merged.
