### ISSUE TITLE
Add method to calculate DDEC6 charges

### ISSUE THREAD

**Issue by mscho527** [cclib/cclib#885]
_This issue is based on the GSoC proposal._

Implementing DDEC6 charges ([sourceforge.net/projects/ddec](url)), as introduced in 10.1039/c6ra04656h, will provide modern atomic charge partitioning method for `cclib`.

Seven steps outlined in the original article can be considered as milestones.

**References**
1. Original Paper (10.1039/c6ra04656h)
2. Related [Video](https://www.youtube.com/watch?v=ao9N9WVjLx0)

**Checklist**
- [x] #914 Add a function to read in proatom densities from chargemol's `atomic_densities`
- [x] #915 Set up the grid and calculate localized charge and stockholder-type charge for DDEC6 [Step 1 of algorithm]
- [x] #916 Calculate reference ion charge value [Step 2 of algorithm]
- [x] #919 Add a function that conditions reference density [Step 3 of algorithm]
- [x] #920 Calculate weights assigned to each grid point in DDEC6 [Step 4-7 of algorithm -- substeps 1~4]
- [x] #921 Add function that evaluates G_A(r_A) and H_A(r_A) for DDEC6 [Step 4-7 of algorithm -- substeps 5~7]
- [x] #922 Add more tests for DDEC6
- [x] #926 Add docs for DDEC6

**Related**
- [x] #917 Add optional weight argument for integrate method in volume **915 depends on this PR**
- [x] #927 Separate out Hirshfeld method from DDEC6 as a standalone method
- [x] #928 Add docs for Hirshfeld
- [x] #930 Clean up DDEC6

**Comment by shivupa** [comment]
Herculean effort! Thanks @mscho527. Closed by #914 #915 #916 #917 #919 #920 #921 #922 #926 #927 #930 #928
