### ISSUE TITLE
Add method to calculate Bader's QTAIM charges

### ISSUE THREAD

**Issue by mscho527** [cclib/cclib#886]
_This issue is based on the GSoC proposal._

Implementation of Bader's QTAIM charges will add modern charge analysis tool for `cclib`. Grid-based integration is also need for determining QTAIM charges.

**References**

1. Calculation of atomic integration data. _J. Computational Chem._ ([Journal](https://onlinelibrary.wiley.com/doi/abs/10.1002/1096-987X%28200009%2921%3A12%3C1040%3A%3AAID-JCC2%3E3.0.CO%3B2-8))
2. Bader Analysis: Calculating the Charge on Individual Atoms in Molecules & Crystals ([Presentation](https://notendur.hi.is/egillsk/stuff/annad/egillsk_bader_pres_150206.pdf))
3. A fast and robust algorithm for Bader decomposition of charge density. _Computational Materials Science_ ([Journal](http://theory.cm.utexas.edu/henkelman/code/bader/download/henkelman06_354.pdf))

**Checklist**

- [x] #893 Add pyquante2 to Travis configuration
- [x] #894 Update pyquante bridge for pyquante2 support
- [x] #896 Update volume method for updated cclib2pyquante bridge
- [x] #897 Add pyquante2 routines in volume method
- [x] #898 \<Bug Fix for existing code\> Fix formula that determine number of grid points in volume function
- [x] #899 Update test routine for volume method to include verify data from each point on a grid
- [x] #900 Add QTAIM method
- [x] #907  Add function to read cube files and generate Volume object; Add the ability to use precalculated charge densities in Bader method
- [x] #902 Add a few more tests for Bader's QTAIM method
- [x] #903 Add docs for QTAIM method
